### ISSUE TITLE
AsyncCacheClient & FileStorage issue

### ISSUE THREAD

**Issue by haron** [karpetrosyan/hishel#143] opened 2023-12-27 12:08 UTC
`AsyncCacheClient` fails to compete a request if configured to use `FileStorage` with a following error:

    AttributeError: 'FileStorage' object has no attribute 'aclose'

More details:
```
> pip freeze | grep -i hishel
hishel==0.0.20

> python -m asyncio
asyncio REPL 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Use "await" directly instead of "asyncio.run()".
Type "help", "copyright", "credits" or "license" for more information.
>>> import asyncio
>>> import hishel
>>> storage=hishel.FileStorage(base_path="/tmp/cache/hishel", ttl=3600)
>>> async with hishel.AsyncCacheClient(storage=storage) as client:
...     await client.get("https://hishel.com")
...
Traceback (most recent call last):
  File "<console>", line 2, in <module>
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/httpx/_client.py", line 1757, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/hishel/_async/_transports.py", line 98, in handle_async_request
    stored_data = await self._storage.retrieve(key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object NoneType can't be used in 'await' expression

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "<console>", line 1, in <module>
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/httpx/_client.py", line 2003, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/hishel/_async/_transports.py", line 243, in __aexit__
    await self.aclose()
  File "/Users/haron/dev/windspeedbot/localpy/lib/python3.11/site-packages/hishel/_async/_transports.py", line 232, in aclose
    await self._storage.aclose()
          ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FileStorage' object has no attribute 'aclose'
```

**Comment by karpetrosyan** [comment] 2023-12-27 12:38
Hi! It's a duplicate of https://github.com/karpetrosyan/hishel/issues/137.
You should just use the relevant asynchronous interface such as `AsyncFileStorage` for the asynchronous clients and transports.

I've already improved the error message, and it will be included in the next release; [see our changelog for more information](https://github.com/karpetrosyan/hishel/blob/master/CHANGELOG.md).

**Closed** 2024-01-02 21:18 UTC
